### ISSUE TITLE
Mis Information

### ISSUE THREAD

**Issue by Kobi-RJP** [DevyusCode/PeyrSharp#165]
### What is the problem?

The ReadMe states that .Net Framework is no longer supported. This is Incorrect, see;

https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

**Comment by Leo-Peyronnet** [comment]
I think I meant that it was no longer in active development, but yes, it is still receiving quality of life/security updates.
I removed that mention to make it clearer.

Thanks for your report.
